# Generated by Django 3.2.9 on 2021-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics')),
                ('special_offer', models.BooleanField(default=False)),
            ],
        ),
    ]
